apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ivanovonews-crawler.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  volumeMode: Filesystem

